version: '3.8'

services:
  project:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/services/project/src
      - static_volume:/opt/services/project/static  # <-- bind the static volume
      - media_volume:/opt/services/project/media  # <-- bind the media volume
    networks:
      - nginx_network
    env_file:
      - ./config/dev.env
    
  

  nginx:
    image: pagespeed/nginx-pagespeed:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/project/static  # <-- bind the static volume
      - media_volume:/opt/services/project/media  # <-- bind the media volume
    depends_on:
      - project
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge


volumes:
  
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume