version: '3.8'

services:
  project:
    build: .
    
    command: gunicorn packaging.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - .:/opt/services/project/src
      - static_volume:/opt/services/project/static  # <-- bind the static volume
      - media_volume:/opt/services/project/media  # <-- bind the media volume
    networks:
      - nginx_network
      - db_network
    env_file:
      - ./config/prod.env
    depends_on:
      - db
  db:
      image: postgres:13.0-alpine
      volumes:
      - db_volume:/var/lib/postgresql/data/
      networks:
      - db_network
      env_file:
      - ./config/prod.env.db
  #volumes:
    #postgres_data:
# To persist the data beyond the life of the container we configured a volume. 
#This config will bind postgres_data to the "/var/lib/postgresql/data/" directory in the container.

  nginx:
    image: pagespeed/nginx-pagespeed:latest
    ports:
      - 800:800
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/project/static  # <-- bind the static volume
      - media_volume:/opt/services/project/media  # <-- bind the media volume
    depends_on:
      - project
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  db_volume:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume